# Generated by Django 4.1 on 2023-11-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aceptado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('confirmation', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'aceptado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=65)),
                ('address', models.CharField(max_length=50)),
                ('personal_phone', models.IntegerField(blank=True, null=True)),
                ('work_phone', models.IntegerField(blank=True, null=True)),
                ('cellphone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'modelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reparaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('budget_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('serial_num', models.CharField(blank=True, max_length=100, null=True)),
                ('failure', models.CharField(blank=True, max_length=250, null=True)),
                ('repair', models.CharField(blank=True, max_length=250, null=True)),
                ('spare_cost', models.IntegerField(blank=True, null=True)),
                ('labor_cost', models.IntegerField(blank=True, null=True)),
                ('pending_payment', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reparaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo',
                'managed': False,
            },
        ),
    ]
